In [4]:
cd ../lib/

/Users/emily/code/AnalysisTools/Python/lib


In [5]:
import assessmentModule as amod
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
%reload_ext autoreload

In [7]:
bike_data = amod.getAssessmentData('567fb06dadac18df718b4568')

In [8]:
bike_oxy_data = amod.getOxyFileFromJSON(bike_data)

In [9]:
amod.getDeviceIDFromOxyFile(bike_oxy_data)

'0CEFAF8109C1'

In [202]:
xx = amod.getDeviceCalibrationRecords('0CEFAF8109C1')

In [204]:
xx.content

b'{"id":"2258","device_id":"0CEFAF8109C1","meta":{"firmware":"1.5.183","model_number":"XM200BLK","type":"IXM"},"hw_version":"197","checkouts":[{"_id":"56255112adac18ee4e8b4579","block":"432-003","calibration_file":"idLeOvrt67pSSZ25QmBlO28SA7qZu5Y7AAAAAGwJ+bqJ0t46+u3rulJJnblCYGU7bxIDupm7ljsAAAAAbAn5uhmu7cSb3LDEHQaaxNoaKcRQQYpHZUEIR64a2kV7koJHOZAxSWoTVklyIyRJ8VZGSbmRbkleAoFJR3tEScTVekmgC9ZJOELiSSG6s0k2xuVJTn4JSijeBUqD6tVJV9sLSslrMUp4sTBKm4EQSiRwPEqG\\/2BK0tRPSp+uK0rXnGNKzIx7SoeVcUoouUpK\\/i+FSuyRnkqeX41K7dFsSudqnkqMa6RKX2yaSk9ohEpnSa5KDZvOSiJwtEqcap1KobHQSteky0q5M7xKj4OkSsYV2EpUXP9KzB\\/cSqaIwkon8gBLvkUOSx6uAEtydehKFGEXS\\/e+MUts4hVLVpUJS2LJM0ueFThLDlEkSyRIGEvJgERLgs1mSzHIP0sM8zRLw65pS1t+eEuuI1tLSy9RS3QshUtkFptLRsd\\/S7AAeEtiIJ5L4MKoSyF7k0vS0pBLE6a1S1So0ksU1atLlH6rS4Hz1kunbOBL1fnCS2UIxEsajvJLkDgMTJCV40sEUuhLm30PTBzNF0wQVgNMquIGTL5\\/JEw8jjxMRvEYTJndH0zgmEJM0FxFTKSpKkyv1jFMEKtWTBlkdUxXuUZMZq5STPndfUw7koJM+r9hTMAwbkzeZY5Mdp+iTHlpg0x4FY1MoVuoTACAqUwEoJFMZu6aTD28t0y+09JMNIWpTA+It0ykMdlMGK3fT

In [11]:
class deviceCheckout():
    def __init__(self, **entries):
        self.__dict__.update(entries)

In [208]:
s = deviceCheckout(**amod.getDeviceCheckoutsFromJSON(xx))

In [210]:
s.calibration_file

'idLeOvrt67pSSZ25QmBlO28SA7qZu5Y7AAAAAGwJ+bqJ0t46+u3rulJJnblCYGU7bxIDupm7ljsAAAAAbAn5uhmu7cSb3LDEHQaaxNoaKcRQQYpHZUEIR64a2kV7koJHOZAxSWoTVklyIyRJ8VZGSbmRbkleAoFJR3tEScTVekmgC9ZJOELiSSG6s0k2xuVJTn4JSijeBUqD6tVJV9sLSslrMUp4sTBKm4EQSiRwPEqG/2BK0tRPSp+uK0rXnGNKzIx7SoeVcUoouUpK/i+FSuyRnkqeX41K7dFsSudqnkqMa6RKX2yaSk9ohEpnSa5KDZvOSiJwtEqcap1KobHQSteky0q5M7xKj4OkSsYV2EpUXP9KzB/cSqaIwkon8gBLvkUOSx6uAEtydehKFGEXS/e+MUts4hVLVpUJS2LJM0ueFThLDlEkSyRIGEvJgERLgs1mSzHIP0sM8zRLw65pS1t+eEuuI1tLSy9RS3QshUtkFptLRsd/S7AAeEtiIJ5L4MKoSyF7k0vS0pBLE6a1S1So0ksU1atLlH6rS4Hz1kunbOBL1fnCS2UIxEsajvJLkDgMTJCV40sEUuhLm30PTBzNF0wQVgNMquIGTL5/JEw8jjxMRvEYTJndH0zgmEJM0FxFTKSpKkyv1jFMEKtWTBlkdUxXuUZMZq5STPndfUw7koJM+r9hTMAwbkzeZY5Mdp+iTHlpg0x4FY1MoVuoTACAqUwEoJFMZu6aTD28t0y+09JMNIWpTA+It0ykMdlMGK3fTJdqvkzJsstM7ufvTHoVC03Qo91MwkvxTOfGDU04zQ1NxLfyTExgAk2DohlNFVQwTco/DU0jcBpNlZE1TZKFOU0DDh9N+4IrTao9SE0drGZNxRw5TbEpS00LoWxNnQJyTQ2hT02HLmBN13yCTY5xlk1LonFNcsaETbswmk0EkJlNgJqETdUzj00YiadNjum+TepQmk1xoKlNbvXFTfMPxU22j6pN5BW4TQo

In [66]:
json.dumps(s.diagnostic_file)

'"{\\"BiasCrossGeometry\\":[0.20054643068568176,0.2941868629508968,0.084778118188352486,0.63720791717083836],\\"CalibrationStatus\\":0,\\"MuEffectiveMeasured\\":[3.008859009242181,2.645330330534847,2.5421757349784837,2.5558779021470088],\\"MuEffectiveNominal\\":[3.031,2.61,2.525,2.56],\\"OpticalDensityNominal\\":[3.39,3.14,3.09,3.112,5.562,5.094,4.998,5.026],\\"RMSErrorCrossGeometry\\":[0.80422576127016077,0.78380346157691594,0.86041879186313652,0.91808619360015686]}\\r\\n{\\"CrossGeometryRMSErrorThreshold\\":6,\\"FullPwrAllCntMaxThreshold\\":[1.16698112E+09,1.12054554E+09,1.20545818E+09,1.41423846E+09,1.38466266E+09,1.19754163E+09,1.22640755E+09,1.465118E+09],\\"FullPwrAllCntMinThreshold\\":[416189952,3.870423E+08,4.264231E+08,5.026023E+08,5.062128E+08,443972352,4.931095E+08,5.847269E+08],\\"MuEffectiveTestMargin\\":0.08}"'

In [119]:
import base64
import struct
import numpy as np

In [240]:
base64.b64decode(s.calibration_file)[:64]

b'\x89\xd2\xde:\xfa\xed\xeb\xbaRI\x9d\xb9B`e;o\x12\x03\xba\x99\xbb\x96;\x00\x00\x00\x00l\t\xf9\xba\x89\xd2\xde:\xfa\xed\xeb\xbaRI\x9d\xb9B`e;o\x12\x03\xba\x99\xbb\x96;\x00\x00\x00\x00l\t\xf9\xba'

In [241]:
invmat = np.fromstring(base64.b64decode(s.calibration_file)[:64], dtype='float32')

In [244]:
np.reshape(invmat[:8], (2, 4))

array([[ 0.0017, -0.0018, -0.0003,  0.0035],
       [-0.0005,  0.0046,  0.    , -0.0019]], dtype=float32)

In [225]:
invC15 = np.reshape(np.fromstring(base64.b64decode(s.calibration_file), dtype='float32')[:8], (2, 4))

In [226]:
invC27 = np.reshape(np.fromstring(base64.b64decode(s.calibration_file), dtype='float32')[8:16], (2, 4))

In [233]:
invC15

array([[ 0.0017, -0.0018, -0.0003,  0.0035],
       [-0.0005,  0.0046,  0.    , -0.0019]], dtype=float32)

In [230]:
invC27

array([[ 0.0017, -0.0018, -0.0003,  0.0035],
       [-0.0005,  0.0046,  0.    , -0.0019]], dtype=float32)

In [239]:
np.fromstring(base64.b64decode(s.calibration_file), dtype='float32')[:64]

array([  1.70000002e-03,  -1.79999997e-03,  -3.00000014e-04,
         3.50000011e-03,  -5.00000024e-04,   4.60000010e-03,
         0.00000000e+00,  -1.90000003e-03,   1.70000002e-03,
        -1.79999997e-03,  -3.00000014e-04,   3.50000011e-03,
        -5.00000024e-04,   4.60000010e-03,   0.00000000e+00,
        -1.90000003e-03,  -1.90144055e+03,  -1.41489392e+03,
        -1.23219104e+03,  -6.76419556e+02,   7.07866250e+04,
         3.48813945e+04,   6.97933496e+03,   6.68529609e+04,
         7.27299562e+05,   8.76854625e+05,   6.72311125e+05,
         8.12399062e+05,   9.77179562e+05,   1.05684375e+06,
         8.04788438e+05,   1.02742025e+06,   1.75346000e+06,
         1.85351100e+06,   1.47232412e+06,   1.88231075e+06,
         2.25269150e+06,   2.19329000e+06,   1.75240038e+06,
         2.29141375e+06,   2.90686625e+06,   2.89494200e+06,
         2.36759075e+06,   3.08736900e+06,   3.68636950e+06,
         3.40510850e+06,   2.81283975e+06,   3.72920575e+06,
         4.12139500e+06,

In [196]:
np.reshape(np.fromstring(base64.b64decode(s.calibration_file)[64:], dtype='float32')/1e9, (25, 8))

array([[ -1.90144056e-06,  -1.41489397e-06,  -1.23219104e-06,
         -6.76419575e-07,   7.07866275e-05,   3.48813955e-05,
          6.97933501e-06,   6.68529610e-05],
       [  7.27299543e-04,   8.76854640e-04,   6.72311115e-04,
          8.12399085e-04,   9.77179618e-04,   1.05684379e-03,
          8.04788433e-04,   1.02742028e-03],
       [  1.75346003e-03,   1.85351097e-03,   1.47232413e-03,
          1.88231072e-03,   2.25269143e-03,   2.19329004e-03,
          1.75240042e-03,   2.29141372e-03],
       [  2.90686614e-03,   2.89494195e-03,   2.36759079e-03,
          3.08736903e-03,   3.68636940e-03,   3.40510858e-03,
          2.81283981e-03,   3.72920581e-03],
       [  4.12139483e-03,   3.95811396e-03,   3.32141807e-03,
          4.36428702e-03,   5.19602187e-03,   4.63252701e-03,
          3.88005935e-03,   5.19102765e-03],
       [  5.38771786e-03,   5.06014330e-03,   4.33872733e-03,
          5.71102742e-03,   6.77005434e-03,   5.91259310e-03,
          5.15822181e-03,   6.8

In [115]:
bike_optical_data = amod.getFileFromJSON(bike_data, 'optical')

In [60]:
x = bike_bsxcsv_data.content.decode()

In [97]:
type(x.split('\n'))

list

In [67]:
column_names = x.split('\n')[2]

In [72]:
len(column_names.split(','))

45

In [107]:
y[0].encode()

b'FLASH_SCHEMA,SAMPLES_PER_SEC,IMU_SAMPLES_PER_SEC,DATE_TIME_UTC,DEVICE_SN,ASSESSMENT_ID,SESSION_TYPE,FW_REV,15mm_ENABLED,30mm_ENABLED,PATHS_15mm@680,PATHS_15mm810,PATHS_15mm@850,PATHS_15mm@970,PATHS_30mm@680,PATHS_30mm810,PATHS_30mm@850,PATHS_30mm@970,IS_DAILY_ACTIVITY,sportType'

In [98]:
y = []
for i in x.splitlines():
    y.append(i)

In [110]:
with open('temp', 'wb') as f:
    for i in y:
        f.write((i +'\n').encode())

In [124]:
    column_names = {}
    if activity == 'run':
        column_names[5] = 'pace'
    else:
        column_names[5] = 'power'
    column_names[0] = 'cHhb_15'
    column_names[1] = 'cHbO2_15'
    column_names[2] = 'cHhb_27'
    column_names[3] = 'cHbO2_27'
    column_names[4] = 'HR'
    column_names[6] = 'time'
    column_names[7] = 'SmO2'
    column_names[8] = 'alert_bits'
    column_names[9] = 'pace_from_IMU'
    column_names[10] = 'unknown'

In [53]:
getDeviceIDFromOxyFile(bike_oxy_data)

'0CEFAF810AFF'

In [25]:
run_data_df = pd.DataFrame(run_oxy_data.json()['result']['content'][1:],
                    columns=None)
bike_data_df = pd.DataFrame(bike_oxy_data.json()['result']['content'][1:],
                    columns=None)

In [31]:
import requests

In [109]:
len(run_data_df.columns)
len(bike_data_df.columns)

11

In [130]:
print("Length of dataset is {0}".format(len(bike_data_df)))
print()
for col in bike_data_df.columns:
    col_name = column_names[col]
    nulls = bike_data_df[col].isnull().sum()
    print("[{0}] Number of missing values: {1}".format(col_name, nulls))

Length of dataset is 10371

[cHhb_15] Number of missing values: 37
[cHbO2_15] Number of missing values: 37
[cHhb_27] Number of missing values: 0
[cHbO2_27] Number of missing values: 0
[HR] Number of missing values: 0
[pace] Number of missing values: 20
[time] Number of missing values: 0
[SmO2] Number of missing values: 0
[alert_bits] Number of missing values: 0
[pace_from_IMU] Number of missing values: 0
[unknown] Number of missing values: 10371


In [114]:
bike_data_df[10].isnull().sum()

10371

In [115]:
len(bike_data_df)

10371

In [28]:
r = amod.getDeviceCalibrationRecords('0CEFAF810AFF')

In [29]:
r.json()

{'checkouts': [{'_id': '563397e2adac18e1658b4570',
   'block': '432-004',
   'calibration_file': 'idLeOvrt67pSSZ25QmBlO28SA7qZu5Y7AAAAAGwJ+bqJ0t46+u3rulJJnblCYGU7bxIDupm7ljsAAAAAbAn5uiPm0Ea006FH46lvR9ejgkfZ0vrIriT2RysAvEcA3YFH4ttgSToyn0lNjXRJESGWSdY+C0mzU75JnJCSSbOGrkkMY99JJFELSt3z20n2eQxKph/MSdw9JUpppAJKQvAjSiUcLkqWREpKZC0jSmdkVErduDFKAn1rSig8P0pOlnZKWUxwSudChUrqdltK19CPSi/6gEooS5xK7kWASijhp0qC3JpKs1amSo18i0pQKLdKDw6rSukDxEq4L6VK+hzXSmJMvkp0hcdKXwqqSpol30rZAtZKc6frShgVyEplOQJLZUkES24YBkvVB+tKEFUZS+gFGEs4BB5LGbQKS7bgM0vWfipLL/8oS4yEF0v9N0RLIKdOS/tvR0tUZTJLytVlS2C7ZUtNnF5LYQVNS2Iwg0vDRIpLH+eCS1dacUtz6ZlLZFOaSzLQkkuwv4pLBTivS/qfuUvH2axL7n2jS9aizUvHG85LvTLBS+LmukvM1OhLLwL3S+f04ksXxNtLvHYITNUfDEyTwAFM+1QATHXCHUwVwidMWWcYTCLaFkwt4ThM6Tw3TL+ZKEx8WClMWetNTJ1QXEwP9UVMaPxGTApVcUwHbHJMt61dTAOgYUxm7IdMrvORTA0fgkzoioRMW06fTLrRnUz+7I5Mq8iSTAa2r0yzQ75ME8anTP5wrEzl8c1M8LnPTNh9uUzjZb9MUO/jTNPC+kwvudlMB9fgTKeUBU38NQVNqt7uTJlz+UwP1hJNk/QgTTUuDE3ughJN+hssTUKcLU22MxtNqDshTaczP01S7VFN7SY2TXxjPU1LHWBNhvBiTS